name: C++ CI

on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
    branches: ['*']
  workflow_dispatch:
    inputs:
      build_type:
        description: Build type
        required: false
        default: 'Debug'
        type: choice
        options:
          - Debug
          - Release
          - RelWithDebInfo
          - MinSizeRel

env:
  BUILD_TYPE: ${{ inputs.build_type || 'Debug' }}
  EXECUTABLE_NAME: "oop"
  INPUT_FILENAME: "input.txt"
  BIN_DIR: "bin"
  BUILD_DIR: "build"
  EXT_DIR: "ext"
  GEN_DIR: "generated"

defaults:
  run:
    shell: bash

jobs:
  valgrind:
    name: "Valgrind: Ubuntu 22.04 GCC 12"
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run cppcheck (Valgrind job mock)
        run: |
          echo "Running Cppcheck for Valgrind mock job"
          cppcheck --version

  asan:
    name: "ASan: Ubuntu 22.04 GCC 12"
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run cppcheck (ASan job mock)
        run: |
          echo "Running Cppcheck for ASan mock job"
          cppcheck --version

  msan:
    name: "MSan: Ubuntu 22.04 Clang 18"
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run cppcheck (MSan job mock)
        run: |
          echo "Running Cppcheck for MSan mock job"
          cppcheck --version

  macos_clang:
    name: "macOS 14 Apple Clang 15"
    runs-on: macos-14
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run cppcheck (macOS Clang job mock)
        run: |
          echo "Running Cppcheck for macOS Clang mock job"
          cppcheck --version

  macos_gcc:
    name: "macOS 14 GCC 13"
    runs-on: macos-14
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run cppcheck (macOS GCC job mock)
        run: |
          echo "Running Cppcheck for macOS GCC mock job"
          cppcheck --version

  windows_msvc:
    name: "ASan: Windows 2022 MSVC 19.41"
    runs-on: windows-2022
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run cppcheck (Windows MSVC job mock)
        run: |
          echo "Running Cppcheck for Windows MSVC mock job"
          cppcheck --version

  windows_mingw:
    name: "Windows 2022 MinGW GCC 13"
    runs-on: windows-2022
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run cppcheck (Windows MinGW job mock)
        run: |
          echo "Running Cppcheck for Windows MinGW mock job"
          cppcheck --version
